--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.6 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: cooking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cooking (id, created_at, title, body) FROM stdin;
1	2023-05-14 19:51:38+00	Day one: I'm going to start cooking more!	Yesterday I made pulled pork for the first time. It felt really good to give back to the family, and more specifically, my wife. I'm making this blog to help inspire me to cook more.
9	2023-07-29 04:37:23.914+00	An update a few months later	I made chili again tonight! That’s my third time and it was the best batch yet. But even more importantly than the taste, I am pleased to report that I’m getting a little more confident in the kitchen. That feels good.\n\nNot that I’ve been cooking a lot, necessarily. I’ve done a few batches of nuts, three attempts at chili, and that’s about it. An omelette here and there, perhaps, and some other easy food I already knew how to make. But it’s something. This is definitely more cooking than I’ve done at any other time in my life, and that’s something.\n\nI also feel like I’m starting to get inspired by ingredients and recipes. It’s not a huge bonfire of inspiration, more like a flickering match. But now that I’ve made food that tastes good, I’m finding myself wondering in the store if I could take that … and combine it with this other thing … and maybe I could make something out of it? And maybe I could even make it taste good? This is a good sign, because as my confidence grows I’ll learn much faster. Here’s hoping!\n\n
2	2023-05-18 19:51:38+00	Some background on my cooking journey	I don't cook much. I can make a homemade pizza. I can throw spaghetti in a big pot, overcook it, and slap some bottled pasta sauce on it. I can make toad-in-a-hole and grilled cheese really well. I can do a thing I call "Jon Soup" which is tomato soup, rice, and chopped sausage. Probably some other things, but you get the point. Bachelor food, low quality, bad for you. (Oh, I made tacos once. And I make sandwiches with deli meats.)\n\nSo that's where I'm coming from. I can feed my kids, technically, but I don't prepare dinners in the traditional way, where I cut vegetables, slave over a hot oven, and so forth. A week of dinners might look like this:\n\n2-3 dinners cooked by Sarah    \n1 night of tater-tots and chicken nuggets  \n1 night of takeaways (I forget how we say that word in America. To-gos?)  \n2-3 nights of leftovers  \n\nWe've been together for 25 years, and I've never been able to cook much. It doesn't mean we sit around and wait for mom to make something. We're more than happy to throw on some pasta, heat up some leftovers, make a homemade pizza, and so forth. There's no *expectation* that Sarah will cook, and for the last two years while she was in school we foraged and did pretty well through her long hours.\n\nBut if we're going to eat real food, the sort of meal you wouldn't be embarrassed to mention cooking for your kids, there is definitely an expectation that if anyone's gonna do it, it's gonna be Sarah. And that's not good, obviously.\n\nThis year, as Mother's Day drew nearer, I told Sarah that as an enlightened husband I know that buying a mom cleaning supplies for Mother's Day is bad. And I think the same goes for cooking breakfast or dinner. In an equal partnership, making ONE MEAL shouldn't be seen as a once-in-a-year treat. So I told her that I was going to make dinner on Sunday, but IT WAS NOT A MOTHER'S DAY PRESENT. JUST SO WE'RE CLEAR.\n\nShe had a good idea. She asked me to take cooking classes, and make *that* my Mother's Day present. Brilliant! I signed up for some classes, and on Mother's Day, my This-Is-Totally-Not-Your-Mother's-Day-Gift dinner was pulled pork cooked with a slow cooker. She told me how to do each step, and I think I should be able to figure it out myself next time.\n\nThe meal went well! (I also did veggies and potatoes) This week we've been living off of leftovers, and now the weekend is drawing near. I've decided this Sunday I'm going to cook something new. I'm thinking about making chilli. We'll see how it goes!\n\n\n\n
13	2024-01-08 14:37:23.914+00	Some recipes to refer to later	<a href="https://www.allrecipes.com/recipe/231808/grandmas-ground-beef-casserole/">Grandma's Hamburger Casserole Recipe</a>\n\n* Ground Beef: 2 packages (500mg each)  \n* Tomato Sauce: 4 cans  \n* White Sugar: 2 teaspoons  \n* Garlic Salt: 2 teaspoons  \n* Salt: 2 teaspoons  \n* Egg Noodles: 2 packages  \n* Diary-free sour cream: 1 container  \n* Greek Yogurt: (to substitute for cream cheese)  \n* Large White Onion: 2 onions, finely diced  \n* Dairy-free cheddar cheese: 1 cup (about 225 grams, or more to taste)\n\n1. Brown the Beef: In a large skillet, cook the ground beef over medium-high heat until browned and crumbly (about 5-7 minutes). Drain and discard the grease.  \n\n2. Prepare Sauce: Add tomato sauce, sugar, garlic salt, and salt to the beef. Simmer for about 20 minutes, then remove from heat.  \n\n3. Cook Noodles: While the sauce simmers, boil a pot of salted water and cook the egg noodles until firm to the bite (7-9 minutes). Drain the noodles.  \n\n4. Preheat Oven: Set your oven to 350 degrees F (175 degrees C).  \n\n5. Mix Creamy Layer: In a bowl, combine sour cream, Greek yogurt (substitute for cream cheese), and diced onion.  \n\n6. Assemble Casserole: In a greased 9x13-inch casserole dish, layer half the egg noodles, half the sour cream mixture, and half the beef mixture. Repeat the layers.  \n\n7. Add Cheese: Sprinkle shredded Cheddar cheese on top.  \n\n8. Bake: Bake in the preheated oven until the cheese is melted and golden brown, about 25-30 minutes.  \n\n--\n\n*Chili Seasoning:*\n\n* Ground Cumin: 1 tablespoon    \n* Fresh Oregano: 1 tablespoon (from your garden)  \n* Cayenne: 1 teaspoon  \n* Paprika: 1 teaspoon  \n\n*Chili:*\n\n* Olive oil: 1 tablespoon  \n* Ground beef: 2 packages (500mg each)  \n* Kosher salt: A bit more than 1/2 teaspoon (adjust to taste)  \n* Black beans: 2 cans  \n* Chili beans: 2 cans  \n* Diced Tomatoes: 2 cans  \n* Tomato Paste: 2 cans    \n* Low-Sodium Chicken Broth: 1 cup  \n* Apple Cider Vinegar: 1 teaspoon  \n\nPreparation Steps:\n\n1. Cook Beef: Heat olive oil in a large pot. Add ground beef and salt, cooking until browned. Drain excess fat.  \n\n2. Add Seasoning: Stir in the chilli seasoning mix.  \n\n3. Combine Ingredients: Add black beans, diced tomatoes, tomato paste, chicken broth, and apple cider vinegar. Include seaweed if desired.  \n\n4. Simmer: Bring to a boil, then reduce heat to simmer. Cook for at least 30 minutes, allowing flavours to blend.  \n\n5. Serve: Adjust seasonings to taste before serving.\n\n
3	2023-05-20 12:51:38+00	The chilli I'm going to make tomorrow	I found a chilli recipe and modified it via chatGPT and Sarah's suggestions. I'm writing it here for posterity, we'll see how it goes tomorrow!\n\nIngredients:\n\nFor the Chili Seasoning:\n\n1 tablespoon ground cumin  \n1 tablespoon fresh oregano (from your garden)  \n1 teaspoon cayenne  \n1 teaspoon paprika  \n\nFor the Chili:\n\n1 tablespoon olive oil  \n1 pound ground beef, preferably ground chuck  \nA bit more than 1/2 teaspoon kosher salt (adjust to taste)  \n2 (15-ounce) cans black beans, drained and rinsed  \n1 (15-ounce) can diced tomatoes  \n1 (6-ounce) can tomato paste  \n1 cup low-sodium chicken broth  \n1 teaspoon apple cider vinegar  \nA little seaweed (optional)  \n\nInstructions:\n\n1. Make the chili seasoning. Place the cumin, fresh oregano, cayenne, and paprika in a small bowl. Whisk with a fork to combine.\n2. Preheat the slow cooker. Set a 4-quart or larger slow cooker to low and allow it to heat while the beef browns.\n3. Brown the ground meat. Heat the oil in a large 10- or 12-inch cast iron skillet over medium-high heat until shimmering. Add the beef, season with the salt, and use a stiff spatula or wooden spoon to break the meat up into large pieces. Let the meat brown without moving for 4 to 5 minutes. Break the meat up into smaller pieces with your spatula and continue to cook until mostly cooked through, 2 to 3 minutes more.\n4. Combine the beef, beans, tomatoes, and broth in the slow cooker. Transfer the browned meat to the slow cooker. Add at least 3 tablespoons of the chili seasoning (save the remainder for another use). Add the beans, tomatoes, tomato paste, and broth. Stir to combine.\n5. Cook on low for 8 hours. Cover and cook the chili on the LOW setting for 8 hours. Avoid stirring it too often or you’ll break down the beans.\n6. Add the cider vinegar and serve. Stir in the cider vinegar just before serving. Serve with garnishes if desired.\n\n
4	2023-05-23 12:51:38+00	I made some chilli!	Two Sundays ago, I made pulled pork by doing what Sarah told me to do. This most recent Sunday, I made chilli from a recipe I found on the internet. (See previous post) It wasn't too bad!\n\nThe main drama of the day is that it was way too spicy for my daughters. 7 hours into the 8 hour cooking time, Sarah stopped by and said "Oh yeah, it's gonna be way too hot. I put in some tomatoes to try and offset it some, but ... we should make something else for them." This is a surprising result, because I only used half of the spices the recipe calls for. I think I measured something wrong.\n\nBut the chilli was good! Elliott had three large bowls, Sarah said she liked it, it was just too hot for her, and I really enjoyed it too. I'm looking forward to trying again. If I can make a version that's zero percent spice, maybe I can even get my daughters to try it.
5	2023-05-29 12:51:38+00	I took a cooking class!	I have a lot to say about this cooking class, but not a lot of time to write. Here's the summary.\n\n* I thought it was going to be super vegan, super hippie, and super sanctimonious\n* It was more level-headed than I was thinking\n* I was blown away by how simple yet delicious the recipes were\n* It was a great class and I got a lot of confidence\n\nOne recipe in particular really jumped out at me, because it's so comically easy:\n\n* Some sort of nuts\n* More nuts\n* Some salt\n* Some other thing\n* Roast them with olive oil on a pan for five minutes\n\nAs soon as I nibbled these, I realised I had a hit. They're salty and delicious, like a snack, but you can use them for all sorts of things. \n\nI also learned how to make real food, not just roasted nuts, but a lot of the recipes were like this. Take some rice, add a variety of super simple yet delicious flavours to the bowl, and voila. A real eye-opener, especially as someone who has frequently been let down by health food that tastes like cardboard. A+ experience.
6	2023-06-01 12:51:38+00	Chilli, round two	This weekend I'm going to try my chilli recipe for the second time.  [Here's the initial post](https://cooking.lot23.com/post/3)\n\nIterating is a lot of fun. Last time here's how it went:\n\n* It wasn't very hard\n* It took 8 hours of cooking though\n* Elliott loved it, I loved it, Sarah sort of loved it (too hot)\n* I didn't even attempt to try it on the girls, I knew it was too hot\n\nSo here are the steps I need to do:\n\n* Make it less hot\n* There is no step two\n\nAlso, bonus, I have an Indian cooking class tomorrow at 6pm. It'll be exciting to learn more!
7	2023-06-05 12:51:38+00	Chilli attempt #2 was successful!	I forgot to strain the beans, so it was very soupy chilli. But overall things went well and they weren't too spicy for the kids! Hurray!
8	2023-06-10 04:37:23.914+00	Dad Crunch was ... ok	I put way too much salt and oil into the Dad Crunch (mixed nuts) when I tried them a few days ago. Next time I think I can do better, and I think adding macadamia nuts is going to help a lot.
11	2023-08-12 14:37:23.914+00	Solo parenting	Sarah's been away from home before, and over the last two years she was in school. During those times, I have a few go-to options to prepare for dinner, so I've leaned on them heavily in the past. Over the last three weeks, Sarah has been away for a job and I'm finding new things to make, which is pretty exciting. Last night I made stir-fry for the first time ever. I've been continuing to hone my chilli recipe. The other day I improvised a sausage and mushroom dish that was much better than I was expecting. It's been fun! 
12	2023-11-25 14:37:23.914+00	Casserole	A few weeks ago I found a casserole recipe online, and it was straight out of the 1940’s Midwest. I loved it. It was dense and creamy and sweet. One of my kids loved it too. And then another kid said it made him feel ill, and Sarah said perhaps I could make it less sweet next time. Hm, decidedly mixed reviews indeed.\n\nSo I made it a second time this week, and did much better! It’s less sweet, less gag-worthy, and overall it worked really well. Sarah liked it a lot more, my son seemed to survive, and the daughter that loved the original batch said this one “tastes like food.” Overall I liked it less, but if they liked it more then that’s what matters most.\n
\.


--
-- Name: cooking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cooking_id_seq', 13, true);


--
-- PostgreSQL database dump complete
--

