/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZJxGGSA1Gja
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Component() {
  return (
    <div>
      <header className="w-full bg-gray-900 py-4 px-6 md:py-6 md:px-8">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" prefetch={false}>
            <FlameIcon className="h-8 w-8 text-white" />
          </Link>
          <h1 className="text-2xl font-bold text-white">Firehose</h1>
        </div>
      </header>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid grid-cols-1 gap-8 px-4 md:grid-cols-3 md:px-6">
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-lg dark:border-gray-800 dark:bg-gray-950">
            <div className="mb-4 flex items-center">
              <FireExtinguisherIcon className="mr-3 h-8 w-8 text-gray-900 dark:text-gray-50" />
              <h3 className="text-xl font-bold">Content Aggregation</h3>
            </div>
            <p className="text-gray-500 dark:text-gray-400">
              Firehose allows you to easily aggregate content from various websites, social media platforms, and RSS
              feeds into a single, unified stream. This enables you to publish your content everywhere and then host it
              on your own site, embracing an IndieWeb approach.
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-lg dark:border-gray-800 dark:bg-gray-950">
            <div className="mb-4 flex items-center">
              <BookIcon className="mr-3 h-8 w-8 text-gray-900 dark:text-gray-50" />
              <h3 className="text-xl font-bold">Publish Everywhere</h3>
            </div>
            <p className="text-gray-500 dark:text-gray-400">
              With Firehose, you can publish your content to multiple platforms simultaneously, including your own
              website, social media channels, and other online destinations. This ensures your message reaches a wider
              audience and helps you maintain a consistent online presence.
            </p>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm transition-all hover:shadow-lg dark:border-gray-800 dark:bg-gray-950">
            <div className="mb-4 flex items-center">
              <ServerIcon className="mr-3 h-8 w-8 text-gray-900 dark:text-gray-50" />
              <h3 className="text-xl font-bold">Host on Your Own Site</h3>
            </div>
            <p className="text-gray-500 dark:text-gray-400">
              Firehose enables you to host the aggregated content on your own website, giving you full control over your
              online presence and data. This aligns with the principles of the IndieWeb, where you own and manage your
              own content, rather than relying on third-party platforms.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full bg-gray-900 py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl space-y-6 text-center text-white">
            <FireExtinguisherIcon className="mx-auto h-16 w-16" />
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Firehose: Your Content Aggregation Solution
            </h2>
            <p className="text-gray-400 md:text-xl/relaxed">
              Firehose is a powerful content aggregation platform that allows you to easily collect and publish your
              content across multiple channels, while maintaining full control over your online presence and data. With
              Firehose, you can embrace the principles of the IndieWeb and take back ownership of your digital content.
            </p>
            <div className="flex justify-center gap-4">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-50 px-6 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700"
                prefetch={false}
              >
                Learn More
              </Link>
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#00b894] px-6 text-sm font-medium text-gray-50 shadow-sm transition-colors hover:bg-[#00a185] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#00b894] disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}
              >
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function FireExtinguisherIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 6.5V3a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v3.5" />
      <path d="M9 18h8" />
      <path d="M18 3h-3" />
      <path d="M11 3a6 6 0 0 0-6 6v11" />
      <path d="M5 13h4" />
      <path d="M17 10a4 4 0 0 0-8 0v10a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2Z" />
    </svg>
  )
}


function FlameIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z" />
    </svg>
  )
}


function ServerIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="8" x="2" y="2" rx="2" ry="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" ry="2" />
      <line x1="6" x2="6.01" y1="6" y2="6" />
      <line x1="6" x2="6.01" y1="18" y2="18" />
    </svg>
  )
}
