name: Update

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:  # This allows you to manually trigger the action.

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run update script
      run: node scripts/update.mjs
