name: Trigger URL

on:
  schedule:
    - cron: '0 */3 * * *'  # At minute 0 past every 3rd hour.
  workflow_dispatch:  # This allows you to manually trigger the action.

jobs:
  hit-url:
    runs-on: ubuntu-latest

    steps:
    - name: Curl request
      run: curl https://firehose.lot23.com/update
